apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hdfs-cluster
  name: namenode-storage-vol
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 101Gi
  storageClassName: azurefile