apiVersion: v1
kind: Service
metadata:
  name: hdfs-master
  namespace: hdfs-cluster
  labels:
    component: hdfs-namenode
    role: master
spec:
  selector:
    component: hdfs-namenode
    role: master
  ports:
  - name: master
    port: 9000
    protocol: TCP
  clusterIP: None