kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: hdfs-cluster
  name: namenode-storage-vol
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: fast
